server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.228.131
aliyun:
  sms:
    accessKeyId: LTAIm2bTapEp5JUc
    accessKeySecret: O5diorohRvlpAnckrOcfARXf6XOu6E
    sign_name: 十次方学习项目
    template_code: SMS_162115196